# Use postgres/example user/password credentials
version: '3.7'

services:

  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432    
    volumes: 
      - nytimespostgres_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:8080
    
  batch:
    build: 
      dockerfile: /src/DockerfileBatch
    container_name: nytimes-batch
    environment:
    - SQLALCHEMY_SILENCE_UBER_WARNING=1
    - NYTIMES_CYPHER_KEY=6v8y/B?E(H+MbQeThWmZq4t7w!z$C&F)
    - NYTIMES_ENV=dev
    tty: true
    stdin_open: true
  
  api:
    build: 
      #context: .
      dockerfile: /src/Dockerfilefastapi
    container_name: api
    environment:
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - NYTIMES_CYPHER_KEY=6v8y/B?E(H+MbQeThWmZq4t7w!z$C&F)
      - NYTIMES_ENV=dev

    ports:
      - 8000:8000
volumes:
  nytimespostgres_db:
    driver: local